admin:
    path:     coc/{id_clan}/admin
    defaults: { _controller: AdminBundle:Default:index }



admin_users:
    path:     coc/{id_clan}/admin/users
    defaults: { _controller: AdminBundle:UserAdmin:index }

admin_user_edit:
    path:     coc/{id_clan}/admin/user/edit/{id}
    defaults: { _controller: AdminBundle:UserAdmin:edit }

admin_user_delete:
    path:     coc/{id_clan}/admin/user/delete/{id}
    defaults: { _controller: AdminBundle:UserAdmin:delete }

admin_user_dissociate:
    path:     coc/{id_clan}/admin/user/dissociate/{id}
    defaults: { _controller: AdminBundle:UserAdmin:dissociate }

admin_user_setAccess:
    path:     coc/{id_clan}/admin/user/role/{id}/{access}
    defaults: { _controller: AdminBundle:UserAdmin:setAccess }



admin_players:
   path:     coc/{id_clan}/admin/players
   defaults: { _controller: AdminBundle:PlayerAdmin:index }

admin_player_add:
    path:     coc/{id_clan}/admin/player/add
    defaults: { _controller: AdminBundle:PlayerAdmin:add }

admin_player_edit:
    path:     coc/{id_clan}/admin/player/edit/{id}
    defaults: { _controller: AdminBundle:PlayerAdmin:edit }

admin_player_delete:
    path:     coc/{id_clan}/admin/player/delete/{id}
    defaults: { _controller: AdminBundle:PlayerAdmin:delete }

admin_players_actual_season:
   path:     coc/{id_clan}/admin/playersActualSaison
   defaults: { _controller: AdminBundle:PlayerAdmin:indexPlayerActualSeason }

admin_player_edit_actual_season:
    path:     coc/{id_clan}/admin/player/actualSeason/{id}
    defaults: { _controller: AdminBundle:PlayerAdmin:editPlayerActualSeason }

admin_players_edit_actual_season:
    path:     coc/{id_clan}/admin/players/actualSeason
    defaults: { _controller: AdminBundle:PlayerAdmin:editPlayersActualSeason }




admin_bestAttacks:
    path:     coc/{id_clan}/admin/bestAttacks
    defaults: { _controller: AdminBundle:BestAttackAdmin:index }

admin_bestAttack_add:
    path:     coc/{id_clan}/admin/bestAttack/add
    defaults: { _controller: AdminBundle:BestAttackAdmin:add }

admin_bestAttack_edit:
    path:     coc/{id_clan}/admin/bestAttack/edit/{id}
    defaults: { _controller: AdminBundle:BestAttackAdmin:edit }

admin_bestAttack_delete:
    path:     coc/{id_clan}/admin/bestAttack/delete/{id}
    defaults: { _controller: AdminBundle:BestAttackAdmin:delete }


admin_bases:
    path:     coc/{id_clan}/admin/bases
    defaults: { _controller: AdminBundle:ImageBaseAdmin:index }

admin_base_add:
    path:     coc/{id_clan}/admin/base/add
    defaults: { _controller: AdminBundle:ImageBaseAdmin:add }

admin_base_edit:
    path:     coc/{id_clan}/admin/base/edit/{id}
    defaults: { _controller: AdminBundle:ImageBaseAdmin:edit }

admin_base_delete:
    path:     coc/{id_clan}/admin/base/delete/{id}
    defaults: { _controller: AdminBundle:ImageBaseAdmin:delete }



admin_wars:
    path:     coc/{id_clan}/admin/wars
    defaults: { _controller: AdminBundle:WarAdmin:index }

admin_war_add:
    path:     coc/{id_clan}/admin/war/add
    defaults: { _controller: AdminBundle:WarAdmin:add }

admin_war_edit:
    path:     coc/{id_clan}/admin/war/edit/{id}
    defaults: { _controller: AdminBundle:WarAdmin:edit }

admin_war_delete:
    path:     coc/{id_clan}/admin/war/delete/{id}
    defaults: { _controller: AdminBundle:WarAdmin:delete }





admin_videos:
    path:     coc/{id_clan}/admin/videos
    defaults: { _controller: AdminBundle:VideoAdmin:index }

admin_video_add:
    path:     coc/{id_clan}/admin/video/add
    defaults: { _controller: AdminBundle:VideoAdmin:add }

admin_video_edit:
    path:     coc/{id_clan}/admin/video/edit/{id}
    defaults: { _controller: AdminBundle:VideoAdmin:edit }

admin_video_delete:
    path:     coc/{id_clan}/admin/video/delete/{id}
    defaults: { _controller: AdminBundle:VideoAdmin:delete }


admin_imagesBonus:
    path:     coc/{id_clan}/admin/imagesBonus
    defaults: { _controller: AdminBundle:ImageBonusAdmin:index }

admin_imageBonus_add:
    path:     coc/{id_clan}/admin/imageBonus/add
    defaults: { _controller: AdminBundle:ImageBonusAdmin:add }

admin_imageBonus_edit:
    path:     coc/{id_clan}/admin/imageBonus/edit
    defaults: { _controller: AdminBundle:ImageBonusAdmin:edit }

admin_imageBonus_delete:
    path:     coc/{id_clan}/admin/imageBonus/delete/{id}
    defaults: { _controller: AdminBundle:ImageBonusAdmin:delete }

admin_clan_edit:
    path:     coc/{id_clan}/admin/clan/edit
    defaults: { _controller: AdminBundle:ClanAdmin:edit }

admin_clan_editPassword:
    path:     coc/{id_clan}/admin/clan/editPassword
    defaults: { _controller: AdminBundle:ClanAdmin:editPassword }

admin_clan_editHiring:
    path:     coc/{id_clan}/admin/clan/editHiring
    defaults: { _controller: AdminBundle:ClanAdmin:editHiring }