services:
    admin.twig.admin_extension:
        class: COC\AdminBundle\Twig\AdminExtension
        tags:
            - { name: twig.extension }

    coc_adminbundle.image_type_extension:
            class: COC\COCBundle\Form\Extension\ImageTypeExtension
            tags:
                - { name: form.type_extension, alias: file }