vitrine_homepage:
    path:     /
    defaults: { _controller: VitrineBundle:Default:index }

coc_clans:
    path:     /clans
    defaults: { _controller: COCBundle:Clan:index }

coc_clan_add:
    path:     /clan/add
    defaults: { _controller: COCBundle:Clan:add }

coc_clan_edit:
    path:     /clan/edit/{id}
    defaults: { _controller: COCBundle:Clan:edit }