coc_homepage:
    path:     /
    defaults: { _controller: COCBundle:Default:index }

coc_players:
    path:     /players
    defaults: { _controller: COCBundle:Player:index }

coc_player_show:
    path:     /player/show/{id}
    defaults: { _controller: COCBundle:Player:show }

coc_player_edit:
    path:     /player/edit/{id}
    defaults: { _controller: COCBundle:Player:edit }

coc_player_add:
    path:     /player/add
    defaults: { _controller: COCBundle:Player:add }

coc_player_delete:
    path:     /player/delete/{id}
    defaults: { _controller: COCBundle:Player:delete }



coc_users:
    path:     /users
    defaults: { _controller: UserBundle:User:index }



coc_user_info:
    path:     /userInfo
    defaults: { _controller: COCBundle:UserInfo:index }

coc_user_info_show:
    path:     /userInfo/{id}
    defaults: { _controller: COCBundle:UserInfo:show }

coc_user_info_edit:
    path:     /userInfo/edit/{id}
    defaults: { _controller: COCBundle:UserInfo:edit }

coc_user_info_add:
    path:     /add
    defaults: { _controller: COCBundle:UserInfo:add }

coc_user_info_delete:
    path:     /delete/{id}
    defaults: { _controller: COCBundle:UserInfo:delete }

coc_users:
    path:     /users
    defaults: { _controller: UserBundle:User:index }

coc_imagesBestAttack:
    path:     /imagesBestAttack
    defaults: { _controller: COCBundle:ImageBestAttack:index }

coc_imageBestAttack_add:
    path:     /imagesBestAttack/add
    defaults: { _controller: COCBundle:ImageBestAttack:add }

coc_imageBestAttack_edit:
    path:     /imagesBestAttack/edit/{id}
    defaults: { _controller: COCBundle:ImageBestAttack:edit }

coc_imageBestAttack_delete:
    path:     /imagesBestAttack/delete/{id}
    defaults: { _controller: COCBundle:ImageBestAttack:delete }


coc_images_base:
    path:     /imagesBase
    defaults: { _controller: COCBundle:ImageBase:index }

coc_images_base_category:
    path:     /imagesBase/category/{id}
    defaults: { _controller: COCBundle:ImageBase:category }

coc_images_base_template:
    path:     /imagesBase/template/{id}
    defaults: { _controller: COCBundle:ImageBase:template }


coc_images_base_add:
    path:     /imagesBase/add
    defaults: { _controller: COCBundle:ImageBase:add }

coc_image_base_edit:
    path:     /imagesBase/edit/{id}
    defaults: { _controller: COCBundle:ImageBase:edit }

coc_image_delete:
    path:     /imagesBase/delete/{id}
    defaults: { _controller: COCBundle:ImageBase:delete }


coc_videos:
    path:     /videos
    defaults: { _controller: COCBundle:Video:index }

coc_video_add:
    path:     /video/add
    defaults: { _controller: COCBundle:Video:add }

coc_video_edit:
    path:     /video/edit/{id}
    defaults: { _controller: COCBundle:Video:edit }

