coc_homepage:
    path:     /
    defaults: { _controller: COCBundle:Default:index }

coc_user_info:
    path:     /userInfo
    defaults: { _controller: COCBundle:UserInfo:index }

coc_user_info_show:
    path:     /userInfo/{id}
    defaults: { _controller: COCBundle:UserInfo:show }

coc_user_info_edit:
    path:     /userInfo/edit/{id}
    defaults: { _controller: COCBundle:UserInfo:edit }

coc_user_info_add:
    path:     /add
    defaults: { _controller: COCBundle:UserInfo:add }

coc_user_info_delete:
    path:     /delete/{id}
    defaults: { _controller: COCBundle:UserInfo:delete }


