services:
#    coc.example:
#        class: COC\COCBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    coc_cocbundle.image_type_extension:
        class: COC\COCBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

    coc_cocbundle.calculate_player_info:
        class: COC\COCBundle\Services\CalculatePlayerInfosService
        arguments: [@doctrine.orm.entity_manager]

