<?php

namespace COC\COCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageBaseRepository extends EntityRepository
{
    public function getNumberEntities($clan)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.clan = :clan')
            ->select('u')
            ->setParameter('clan', $clan);

        return count($qb->getQuery()->getResult());
    }
}
