<?php

namespace COC\COCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageBestAttackRepository extends EntityRepository
{
    public function getBestAttacks()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.elixir + u.gold', 'DESC');


        //var_dump($qb->getQuery()->getResult());
        return $qb->getQuery()->getResult();
    }

    public function getNumberBestAttacks()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u');

        return count($qb->getQuery()->getResult());
    }
}
