<?php

namespace COC\COCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function getImagesByCategory($category)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.categoryImage = :category')
            ->setParameter('category', $category);

        return $qb->getQuery()->getResult();
    }
}
