<?php

namespace COC\COCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class playerRepository extends EntityRepository
{
    public function getHistory()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.updatedAt', 'DESC')
            ->setMaxResults( 3 );
        //var_dump($qb->getQuery()->getResult());
        return $qb->getQuery()->getResult();
    }
}