<?php

namespace COC\COCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerHistoryRepository extends EntityRepository
{
    public function getLastUpdate($clan)
    {
        $query = $this->_em->createQuery('SELECT m.updatedAt FROM COCBundle:PlayerHistory m WHERE m.clan = :clan ORDER BY m.updatedAt DESC')
            ->setMaxResults(1)
            ->setParameter('clan', $clan);

        return $query->getOneOrNullResult();
    }


    public function findBySeason($season, $clan)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.season = :season')
            ->andWhere('p.clan = :clan')
            ->orderBy('p.level', 'DESC')
            ->setParameter('clan', $clan)
            ->setParameter('season', $season);

        return $qb->getQuery()->getResult();
    }



    public function findActivityBySeason($season, $clan)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p.id, p.level, p.name, p.troopSent, p.troopReceived, p.attackWon, p.trophy, p.hallTown, p.updatedAt, p.name')
            ->where('p.season = :season')
            ->andWhere('p.clan = :clan')
            ->orderBy('p.attackWon', 'DESC')
            ->setParameter('clan', $clan)
            ->setParameter('season', $season)
           ;

        return $qb->getQuery()->getResult();
    }


}