# src/Uae/UserBundle/Resources/config/services.yml
services:
    application_user.clan_registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationClanFormType
        arguments: [ @doctrine.orm.entity_manager,  @security.context ]
        tags:
            - { name: form.type, alias: clan_registration }

